#!/bin/sh

ACTION=$1

# Helper function to adjust permissions
change_permissions() {
    local dir=$1
    chown -R :www-data $dir
    find $dir -type f -exec chmod 664 {} \;
    find $dir -type d -exec chmod 775 {} \;
}

case $ACTION in

  frontend:load)
      echo "Loading frontend..."
      # If a pre-build frontend exists, use it to speed up the startup
      if [ -f "/var/www/html/public/build/next/manifest.json" ]; then
          echo "Pre-build frontend found, use it to speed up the startup"
          # Clean up the assets directory
          rm -r /var/www/html/public/build/assets
          # Copy the pre-build frontend to the build folder
          cp -r /var/www/html/public/build/next/assets /var/www/html/public/build/assets
          cp /var/www/html/public/build/next/manifest.json /var/www/html/public/build/manifest.json
          cp /var/www/html/public/build/next/hash /var/www/html/public/build/hash
      else
          pilos-cli frontend:build
      fi
      ;;

  frontend:build)
    su-exec www-data /usr/local/etc/frontend/run.sh
    ;;

  frontend:pre-build)
    su-exec www-data /usr/local/etc/frontend/run.sh --pre-build
    ;;

  playback-player:build)
    su-exec www-data /usr/local/etc/playback-player/build.sh $2
    ;;

  change-permissions)
    echo "Change permissions"
    change_permissions /var/www/html/resources/custom
    change_permissions /var/www/html/storage/app
    change_permissions /var/www/html/storage/logs
    change_permissions /var/www/html/public/build
    ;;

  create-spool-group)
    # Create spool group and add www-data to it
    # PILOS_SPOOL_GID is 2000 by default
    echo "Creating spool group with GID $PILOS_SPOOL_GID"
    addgroup pilos-spool --gid ${PILOS_SPOOL_GID}
    adduser www-data pilos-spool
    ;;

  optimize)
      pilos-cli config:cache
      pilos-cli route:cache
      pilos-cli view:cache
      pilos-cli event:cache
      pilos-cli locales:cache
    ;;

  optimize:clear)
      su-exec www-data composer dump-autoload
      pilos-cli config:clear
      pilos-cli route:clear
      pilos-cli view:clear
      pilos-cli event:clear
      pilos-cli cache:clear
    ;;

  init)
    pilos-cli change-permissions
    pilos-cli create-spool-group
    pilos-cli frontend:load
    pilos-cli optimize
    ;;

  run:horizon)
    pilos-cli create-spool-group
    su-exec www-data php artisan horizon
    ;;

  run:cron)
    pilos-cli create-spool-group
    /usr/sbin/crond -f
    ;;

  *)
    ARGS=${@}
    su-exec www-data php artisan $ARGS
    ;;
esac
