#!/usr/bin/env bash

ACTION=$1

case $ACTION in

  build-frontend)
    su-exec www-data /usr/local/etc/frontend/run.sh
    ;;

  change-permissions)
    chown -R :www-data /var/www/html/resources/custom
    chown -R :www-data /var/www/html/resources/sass/theme/custom
    chown -R :www-data /var/www/html/storage/
    find /var/www/html/resources/custom/ -type f -exec chmod 664 {} \;
    find /var/www/html/resources/custom/ -type d -exec chmod 775 {} \;
    find /var/www/html/resources/sass/theme/custom/ -type f -exec chmod 664 {} \;
    find /var/www/html/resources/sass/theme/custom/ -type d -exec chmod 775 {} \;
    find /var/www/html/storage/ -type f -exec chmod 664 {} \;
    find /var/www/html/storage/ -type d -exec chmod 775 {} \;
    ;;

  optimize)
      su-exec www-data composer dump-autoload -o
      pilos-cli config:cache
      pilos-cli route:cache
      pilos-cli view:cache
      pilos-cli event:cache
      pilos-cli locales:cache
    ;;

  optimize:clear)
      su-exec www-data composer dump-autoload
      pilos-cli config:clear
      pilos-cli route:clear
      pilos-cli view:clear
      pilos-cli event:clear
      pilos-cli cache:clear
    ;;

  init)
    pilos-cli change-permissions
    pilos-cli build-frontend
    pilos-cli migrate --force --isolated --seed
    pilos-cli storage:link
    pilos-cli optimize
    ;;

  *)
    ARGS=${@}
    su-exec www-data php artisan $ARGS
    ;;
esac
