#!/usr/bin/env bash

ACTION=$1

case $ACTION in

  build-frontend)
    gosu www-data /usr/local/etc/frontend/run.sh
    ;;

  change-permissions)
    chown -R :www-data /var/www/html/resources/custom
    chown -R :www-data /var/www/html/resources/sass/theme/custom
    chown -R :www-data /var/www/html/storage/app
    chown -R :www-data /var/www/html/storage/logs
    find /var/www/html/resources/custom/ -type f -exec chmod 664 {} \;
    find /var/www/html/resources/custom/ -type d -exec chmod 775 {} \;
    find /var/www/html/resources/sass/theme/custom/ -type f -exec chmod 664 {} \;
    find /var/www/html/resources/sass/theme/custom/ -type d -exec chmod 775 {} \;
    find /var/www/html/storage/ -type f -exec chmod 664 {} \;
    find /var/www/html/storage/ -type d -exec chmod 775 {} \;
    ;;

  optimize)
      gosu www-data composer dump-autoload -o
      pilos-cli config:cache
      pilos-cli route:cache
      pilos-cli view:cache
      pilos-cli locales:cache
    ;;

  init)
    pilos-cli change-permissions
    pilos-cli build-frontend
    pilos-cli migrate --force --isolated --seed
    pilos-cli storage:link
    pilos-cli optimize
    ;;  

  *)
    ARGS=${@}
    gosu www-data php artisan $ARGS
    ;;
esac