# Prevent IFRAME spoofing attacks
# See: https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-frame-options
add_header X-Frame-Options "DENY" always;

# Prevent MIME attacks
# See: https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-content-type-options
add_header X-Content-Type-Options "nosniff" always;

# Prevent Referrer URL from being leaked
# See: https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#referrer-policy
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Disable XSS protection
# See: https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-xss-protection
add_header X-XSS-Protection "0" always;

# Prevent cross-origin window.opener access (COOP)
# See: https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#cross-origin-opener-policy-coop
add_header Cross-Origin-Opener-Policy "same-origin" always;
