{
 "title": "PILOS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests/sec.",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pilos_request_total{code=~\"1xx|2xx|3xx\"}[$__rate_interval]))",
     "legendFormat": "1/2/3xx"
    },
    {
     "expr": "rate(pilos_request_total{code!~\"1xx|2xx|3xx\"}[$__rate_interval])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pilos_request_duration_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Request memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pilos_request_memory_bytes", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Queue Workload",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "pilos_horizon_current_workload", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Server Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pilos_servers_total{status=\"online\"}"
    },
    {
     "expr": "pilos_servers_total{status=\"disabled\"}"
    },
    {
     "expr": "pilos_servers_total{status=\"draining\"}"
    },
    {
     "expr": "pilos_servers_total{status=\"offline\"}"
    },
    {
     "expr": "pilos_servers_total{status=\"faulty\"}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pilos_users_total" }
   ]
  },
  {
   "title": "Rooms",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pilos_rooms_total" }
   ]
  },
  {
   "title": "Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pilos_files_total" }
   ]
  },
  {
   "title": "Recordings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pilos_recordings_total" }
   ]
  },
  {
   "title": "Horizon Status",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "targets": [
    { "expr": "pilos_horizon_status" }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pilos_active_sessions_total" }
   ]
  },
  {
   "title": "Total Meetings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pilos_meetings_total" }
   ]
  },
  {
   "title": "Running Meetings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pilos_running_meetings_total" }
   ]
  },
  {
   "title": "Jobs/Minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pilos_horizon_jobs_per_minute" }
   ]
  },
  {
   "title": "Failed Jobs/Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pilos_horizon_failed_jobs_per_hour"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(pilos_login_total[1m]))",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(increase(pilos_login_failed_total[1m]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Room Joins",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "changes(pilos_room_joined_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Room Start: No Server Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pilos_room_start_errors_total{error_type=\"no_server_found\"}[1m])"
    }
   ]
  },
  {
   "title": "Room Start: Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pilos_room_start_errors_total{error_type=\"start_failed\"}[1m])"
    }
   ]
  },
  {
   "title": "Room Guest Access Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pilos_room_authentication_errors_total{error_type=\"guest_access\"}[1m])"
    }
   ]
  },
  {
   "title": "Jobs/Minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pilos_horizon_jobs_per_minute" }
   ]
  },
  {
   "title": "Room Starts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "changes(pilos_room_started_total[1m])"
    }
   ]
  },
  {
   "title": "Room Join: Not running on Server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pilos_room_join_errors_total{error_type=\"meeting_not_running_on_server\"}[1m])"
    }
   ]
  },
  {
   "title": "Room Join: Checking Server Error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pilos_room_join_errors_total{error_type=\"checking_meeting_running_on_server_error\"}[1m])"
    }
   ]
  },
  {
   "title": "Invalid Pers. Room Links",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pilos_room_authentication_errors_total{error_type=\"token\"}[1m])"
    }
   ]
  },
  {
   "title": "Invalid Access Code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pilos_room_authentication_errors_total{error_type=\"access_code_invalid\"}[1m])"
    }
   ]
  }
 ]
}