# SPDX-FileCopyrightText: 2023 Technische Hochschule Mittelhessen (THM) and PILOS contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    groups:
      tiptap:
        patterns:
          - "@tiptap*"
      primevue:
        patterns:
          - "primevue*"
          - "@primevue*"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    groups:
      laravel:
        patterns:
          - "laravel/*"
      phpunit:
        patterns:
          - "brianium/paratest"
          - "phpunit/phpunit"

  # Github Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
  # Docs dependencies for npm
  - package-ecosystem: "npm"
    directory: "/docs"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    groups:
      docs:
        patterns: ["*"]
        update-types: ["minor", "patch"]
