# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
            args:
              WWWGROUP: '${WWWGROUP}'
              WWWUSER: '${WWWUSER}'
        ports:
          - '${APP_PORT:-80}:80'
          - '${APP_SSL_PORT:-443}:443'
          - '${VITE_PORT:-1073}:${VITE_PORT:-1073}'
          - '${VITEST_UI_PORT:-1074}:${VITEST_UI_PORT:-1074}'
        environment:
          ENABLE_XDEBUG: '${ENABLE_XDEBUG:-no}'
          TRUSTED_PROXIES: "*"
        volumes:
          - './:/var/www/html/'
          - './ssl:/local/certs/'
        depends_on:
          - db
    db:
      image: 'mariadb:10'
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - 'mariadb:/var/lib/mysql'
        - './tests/Utils/create-mysql-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-u${DB_USERNAME}", "-p${DB_PASSWORD}" ]
        retries: 3
        timeout: 5s
    redis:
      image: redis:7.2-alpine3.18
      restart: unless-stopped
      volumes:
        - redis:/data
    mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
        - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - '${FORWARD_PHPMYADMIN_PORT:-8080}:80'
      environment:
        MYSQL_USERNAME: "${DB_USERNAME}"
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        PMA_HOST: db
        PMA_USER: "${DB_USERNAME}"
        PMA_PASSWORD: "${DB_PASSWORD}"
        UPLOAD_LIMIT: 2G
    openldap:
      image: osixia/openldap
      environment:
        LDAP_ORGANISATION: "Demo University"
        LDAP_DOMAIN: "university.org"
        LDAP_READONLY_USER: 'true'
      volumes:
        - './docker/openldap:/container/service/slapd/assets/config/bootstrap/ldif/custom'
      command: --copy-service
    phpldapadmin:
      image: osixia/phpldapadmin
      ports:
        - '${FORWARD_PHPLDAPADMIN_PORT:-6680}:80'
      environment:
        PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'Local LDAP': [{'server': [{'host': 'openldap'}]},{'login': [{'bind_id': 'cn=admin,dc=university,dc=org'},{'bind_pass': 'admin'},{'auth_type': 'config'}]}]}]"
        PHPLDAPADMIN_HTTPS: 'false'
volumes:
  mariadb:
    driver: local
  redis:
    driver: local  
