# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
        image: pilos/pilos:latest
        ports:
          - '${APP_PORT:-80}:80'
        environment:
          ENABLE_XDEBUG: '${ENABLE_XDEBUG:-no}'
        volumes:
          - './:/var/www/html/'
        depends_on:
          - db
    db:
      image: 'mariadb:10'
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-u${DB_USERNAME}", "-p${DB_PASSWORD}" ]
        retries: 3
        timeout: 5s
