[PHP]
; =========================
; File Upload Settings
; =========================
; Max size of POST data allowed. Default: 8M. Increased for large uploads
post_max_size           = 1G
; Max size of an uploaded file. Default: 2M. Increased for large uploads, is limited using BBB_MAX_FILESIZE in application
upload_max_filesize     = 1G
; Whether to allow HTTP file uploads. Default: On
file_uploads            = On
; Max. number of files that can be uploaded via a single request. Default: 20; Currently the application only has max. of 8 file inputs in a form
max_file_uploads        = 20

; =========================
; Error Handling and Logging
; =========================
; Report all PHP errors. Default: E_ALL
error_reporting         = E_ALL
; Do not display errors to users. Default: On. Set Off for security
display_errors          = Off
; Do not display startup errors. Default: On. Set Off for security
display_startup_errors  = Off
; Log errors to file. Default: Off. Set On for production, as logs are not displayed
log_errors              = On
; Log file location. Default: (none). Set to stderr for container logging
error_log               = /dev/stderr
; Do not ignore repeated errors. Default: Off
ignore_repeated_errors  = Off
; Report memory leaks. Default: On
report_memleaks         = On

; =========================
; Security Settings
; =========================
; Do not expose PHP version in headers. Default: On. Set Off for security
expose_php              = Off
; Disable URL-aware fopen wrappers. Default: On. Set Off for security
allow_url_fopen         = Off
; Disable URL include/require. Default: Off
allow_url_include       = Off
; Disable dynamic loading of extensions. Default: On. Set Off for security
enable_dl               = Off
; Disable WebDAV methods. Default: Off.
allow_webdav_methods    = Off

; =========================
; Resource Limits
; =========================
; Max memory per script. Default: 128M. Increased for resource-intensive operations
memory_limit            = 512M
; Max execution time (seconds). Default: 30
max_execution_time      = 30
; Max time to parse input (seconds). Default: 60. -1 means max_execution_time is used
max_input_time          = -1

; =========================
; Input Variables Order
; =========================
; Order of GET, POST, COOKIE, SERVER vars. Default: "EGPCS"
variables_order         = GPCS
; Order for $_REQUEST. Default: "EGPCS"
request_order           = "GP"
