// SPDX-FileCopyrightText: 2026 Technische Hochschule Mittelhessen (THM) and PILOS contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

export const HTTP_STATUS_UNAUTHORIZED = 401;
export const HTTP_STATUS_FORBIDDEN = 403;
export const HTTP_STATUS_NOT_FOUND = 404;
export const HTTP_STATUS_GONE = 410;
export const HTTP_STATUS_PRECONDITION_FAILED = 412;
export const HTTP_STATUS_PAYLOAD_TOO_LARGE = 413;
export const HTTP_STATUS_GUESTS_ONLY = 420;
export const HTTP_STATUS_UNPROCESSABLE_ENTITY = 422;
export const HTTP_STATUS_ROOM_NOT_RUNNING = 460;
export const HTTP_STATUS_NO_SERVER_AVAILABLE = 461;
export const HTTP_STATUS_ROOM_START_FAILED = 462;
export const HTTP_STATUS_ROOM_LIMIT_EXCEEDED = 463;
export const HTTP_STATUS_ROLE_DELETE_LINKED_USERS = 464;
export const HTTP_STATUS_ROLE_UPDATE_PERMISSION_LOST = 465;
export const HTTP_STATUS_FEATURE_DISABLED = 468;
export const HTTP_STATUS_MEETING_ATTENDANCE_NOT_ENDED = 469;
export const HTTP_STATUS_MEETING_ATTENDANCE_DISABLED = 470;
export const HTTP_STATUS_EMAIL_CHANGE_THROTTLE = 471;
export const HTTP_STATUS_JOIN_FAILED = 472;
export const HTTP_STATUS_ROOM_ALREADY_RUNNING = 474;
export const HTTP_STATUS_STALE_MODEL = 428;
export const HTTP_STATUS_TOO_MANY_REQUESTS = 429;
export const HTTP_STATUS_LOCKED = 423;
export const HTTP_STATUS_SERVICE_UNAVAILABLE = 503;
